AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Photo Album - CloudFormation Stack'

Parameters:
  OpenSearchEndpoint:
    Type: String
    Default: search-photos-ef4nehxeanhqk4ourwtldsail4.us-east-1.es.amazonaws.com
    Description: OpenSearch domain endpoint
  
  OpenSearchIndex:
    Type: String
    Default: photos
    Description: OpenSearch index name

Resources:
  PhotoStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'photo-storage-cfn-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'photo-frontend-cfn-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRekognitionFullAccess

  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos-cfn
      Runtime: python3.14
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              print("Index photos function")
              return {'statusCode': 200}

  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos-cfn
      Runtime: python3.14
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'headers': {'Access-Control-Allow-Origin': '*'},
                  'body': json.dumps({'results': [], 'count': 0})
              }

  PhotoAlbumAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: AI-Photo-Search-CFN

  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt PhotoAlbumAPI.RootResourceId
      PathPart: search
      RestApiId: !Ref PhotoAlbumAPI

  SearchMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosFunction.Arn}/invocations'

  SearchLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SearchPhotosFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoAlbumAPI}/*/*/*'

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - SearchMethod
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      StageName: prod

Outputs:
  FrontendURL:
    Description: Frontend Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL

  APIEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub 'https://${PhotoAlbumAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'
